#+Title:  Roadmap for Integration Team for 2 weeks
#+Author: Integration Team
#+Date:   <2015-09-23 Wednesday>

* Current Status: 

** For First set of labs
*** Sources available for 16 labs 
Linux lab is at L4, rest of the labs are at L6.

*** Sources partially available for 2 labs 
Data Structures and Physical Chemistry

*** Sources not available for 2 labs 
Pattern Recognition and EM Theory


** For second set of labs
*** Sources available for 7 labs 
Molecular Absorption Spectroscopy, Computational Linguistics,
Structural Dynamics, Soil Mechanics and Foundation Engineering,
Molecular Florescence Spectroscopy, Analog CMOs VLSI Circuit Design
and Principles of Programming Languages.

*** Sources partially available for 3 labs 
Circular Dichronism Spectroscopy, Speech Signal Processing and Colloid and Surface Chemistry

*** Sources not available for 6 labs 
Physical Science Lab, Mobile Robotics, Quantum Chemistry, Optical
Remote Sensing, Geotechnical Engineering Lab and Molecular
Interactions


* TODO 

1) Data Structures lab :: Khushpreet 

-  Explain work flow to RA's, coordinate with them and review their
   work on timely basis.

2) Physical chemistry lab :: Sravanthi

- Need to setup environment for Java 3D and get the source code for 2
  experiments.

- Write test cases for each experiment.

3) Pattern Recognition:: Sadhana

- Need to get the source code for 8 experiments.

- Write test cases for each experiment.


4) Automation Script :: Khushpreet

- Coordinate with Siddharth and review his work.

5) Computer Programming Lab :: Khushpreet 

- Resolve issue of 10th experiment (Expression Evaluation) and host it
  with new src code.


Deadline for these tasks is [2015-10-07 Wednesday]


